### PR TITLE
Compile on Fedora

### PR DESCRIPTION
**Pull request by misaelnieto**
So This is what it takes to compile on Fedora 27

### CODE REVIEW

**Comment by tcaduser** [comment]
Thank you for your pull request.  Unfortunately, I moved the master to old_master.  I then rewrote the master.  This was to fix the email address of some commits, so that juanesanchez would not show up as a contributor, since he had taken my old username.

Would you please be able to resubmit your pull request, based on the new master?

**Comment by tcaduser** [comment]
In addition, you can remove Miniconda from your script, since that is a python distribution, and you are using the system version.

**Comment by misaelnieto** [comment]
So I can remove miniconda. Great.

I'm a bit confusedI deleted my previous fork and re-forked the devsim repository yesterday during the night and your last commit is from three years ago. I believe I already have right master branch.

**Comment by tcaduser** [comment]
Thank you for your submission.

The conflicts from 3 years ago are because I rewrote the history from that time.  I managed to create a diff and apply your changes onto the new repository history.  In addition, I made changes to the build script so that it will also build in a Docker container, which runs as root.

I have verified that the software builds, and I was able to run a simple test.

**Comment by misaelnieto** [comment]
Ohhhhh I'm sorry, I wrote 3 years instead of "3 days". 
It should have read:
I deleted my previous fork and re-forked the devsim repository **yesterday** during the night and your last commit is from **three days ago**. I believe I already have right master branch.
My apologies.

**Pull request closed without merging**
