### PR TITLE
Proposal: Enforce Python formatting

### PR DESCRIPTION
**Pull request by simbilod**
*Description of changes:*

This is a followup to #139. 

This PR adds [ruff](https://docs.astral.sh/ruff/) [pre-commit](https://pre-commit.com/) instructions (.pre-commit-config.yaml) to enforce Python formatting. It also adds a Github Actions workflow (.github/workflows/pre_commit.yml) to check this formatting server-side.

The "Contributing" section has been expanded to explain this. The formatting configuration for Python is stored in ruff.toml (currently using defaults, and adding some more excluded directories).

If this is a good idea, in a followup PR, we can add clang pre-commit to autoformat the C++ as well.

*Licensing*

To maintain the integrity of the project, we require contributions to be licensed under the Apache License Version 2.0. Please acknowledge this by checking the box below. By checking the box, you also acknowledge that you have the authority to license your contribution in this manner. You should also ensure that any new file you add contains "# SPDX-License-Identifier: Apache-2.0" in the header.

 - [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](https://apache.org/licenses/LICENSE-2.0).

### CODE REVIEW

**Comment by tcaduser** [comment]
My only concern is I don't want to have too much reliance on the Microsoft-GItHub ecosystem.

I do like the option of having a precommit hook that can be run.

I don't want to autoformat c++ at this time, because that would result in massive changes in the repository.

Is there a way to ensure that python 3.7 or 3.8 is supported?

**Comment by simbilod** [comment]
> My only concern is I don't want to have too much reliance on the Microsoft-GItHub ecosystem.

That should be fine, if the code migrates to another repository platform (e.g. Gitlab), there server-side "actions" equivalents.

> I do like the option of having a precommit hook that can be run.

Yes, this can always be done manually. You could even not have Github check it and just enforce it as part of the PR review.

> I don't want to autoformat c++ at this time, because that would result in massive changes in the repository.

Makes sense. I'm just used to navigating codebases having standard formatting, so going through this one was slightly more challenging :)

> Is there a way to ensure that python 3.7 or 3.8 is supported?

3.7 has reached end-of-life, but yes, I think everything that has been added here is version-agnostic
* I have modified the formatting version to py37 (so minimally Python 3.7) in commit [bba1422](https://github.com/devsim/devsim/pull/140/commits/bba1422d5b0f0cd381150712dd27965c31fe3b0a). It did not format the code differently.
* We choose a version for the runner doing the server-side check [here](https://github.com/simbilod/devsim/blob/55166352f2bbd82fc0abcc36adebb0d8a7f0f8f2/.github/workflows/pre_commit.yml#L21), 3.10 currently, but it will use the formatting specified in `ruff.toml`

**Comment by simbilod** [comment]
If you ever were interested in adding C++ formatting, adding the following to `pre-commit-config.yaml` [would do the trick](https://github.com/ssciwr/clang-format-wheel):

```

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.6
  hooks:
  - id: clang-format
    types_or: [c++, c, cuda]
```

You can add a file called `.clang_format` to the repo to store settings, as explained e.g. in [here](https://clangpowertools.com/blog/getting-started-with-clang-format-style-options.html)

**Comment by tcaduser** [comment]
> > I don't want to autoformat c++ at this time, because that would result in massive changes in the repository.
> 
> Makes sense. I'm just used to navigating codebases having standard formatting, so going through this one was slightly more challenging :)
> 

What exactly is "standard formatting"?  The formatting I have tried to apply is:
* 2 space (maybe change to 4 space) tab stops
* no tab characters for indentation
* no trailing whitespace, unless it is in multiline string

In vim, this amounts to:
ts=2 sts=2 sw=2 et

Opening curly brace is always the next line after the statement for conditionals, for loops, etc:
```
  if (.....)
  {
  }
  else if (....)
  {
  }
  else
  {
  }

  for (...; ....; ....)
  {
  }
```
I would prefer all statements in a curly braces, even single lines.
```
    if (....)
    {
         single statement here
    }
```

Anyway, anything for c++ should be a separate PR.

Also, I don't know what tools you are using for navigation, but I think that both VS code and  clion are free for open source development.  I use gvim, but I know the code base since I've been developing it for 15 years.

Have you ever experimented with editorconfig?

https://editorconfig.org/

**Comment by tcaduser** [comment]
Also, while I saw that ruff (for python) is not compatible with this, any c++ autoformat solution should not modify existing software code.

**Comment by simbilod** [comment]
> Also, I don't know what tools you are using for navigation, but I think that both VS code and clion are free for open source development. I use gvim, but I know the code base since I've been developing it for 15 years.
> 
> Have you ever experimented with editorconfig?
> 
> https://editorconfig.org/

I use VSCode and [Intellisense ](https://code.visualstudio.com/docs/editor/intellisense) did a good job to help me navigate. The actual formatting is just a minor point :)

**Comment by tcaduser** [comment]
merged, thanks

**Pull request closed without merging**
